<?php

namespace ContainerJyAlI49;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V7Lt_0FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v7Lt.0F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v7Lt.0F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\MainController::consultation' => ['privates', '.service_locator.Wo5Rpgu', 'get_ServiceLocator_Wo5RpguService', true],
            'App\\Controller\\MainController::listAll' => ['privates', '.service_locator.Wo5Rpgu', 'get_ServiceLocator_Wo5RpguService', true],
            'App\\Controller\\MainController::rdv' => ['privates', '.service_locator.Wo5Rpgu', 'get_ServiceLocator_Wo5RpguService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MainController:consultation' => ['privates', '.service_locator.Wo5Rpgu', 'get_ServiceLocator_Wo5RpguService', true],
            'App\\Controller\\MainController:listAll' => ['privates', '.service_locator.Wo5Rpgu', 'get_ServiceLocator_Wo5RpguService', true],
            'App\\Controller\\MainController:rdv' => ['privates', '.service_locator.Wo5Rpgu', 'get_ServiceLocator_Wo5RpguService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MainController::consultation' => '?',
            'App\\Controller\\MainController::listAll' => '?',
            'App\\Controller\\MainController::rdv' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MainController:consultation' => '?',
            'App\\Controller\\MainController:listAll' => '?',
            'App\\Controller\\MainController:rdv' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
