<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVyiTir0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVyiTir0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVyiTir0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVyiTir0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVyiTir0\App_KernelDevDebugContainer([
    'container.build_hash' => 'VyiTir0',
    'container.build_id' => '9c3b7a99',
    'container.build_time' => 1736515465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVyiTir0');
